{% set name = "fps-uvicorn" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_uvicorn-0.0.19.tar.gz
  sha256: 249556e6920d3a56e11bef42adbd64944f210ddfb8b0208ca3caadc9764f8b0a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install ./plugins/uvicorn/ --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - fps-uvicorn = fps_uvicorn.cli:app

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps
    - uvicorn

test:
  imports:
    - fps_uvicorn

about:
  home: https://github.com/jupyter-server/fps
  summary: A uvicorn plugin for FPS
  description: A uvicorn plugin for FPS
  keywords: asgi, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/fps
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - adriendelsalle
    - davidbrochart
